import type { Locale } from '@/lib/preferences'

const ZH = {
  title: '威科夫纸面影子账',
  subtitle: '漏斗纸面对照账户，不是实盘成交。',
  disclaimer: '策略按威科夫漏斗跑纸面账；非投资建议',
  showcaseBadge: '橱窗摘要',
  fullBadge: '完整账本',
  navTitle: '累计净值曲线',
  periodPnl: '区间净收益',
  periodPct: '区间收益',
  maxDrawdown: '最大回撤',
  winRate: '粗胜率',
  openCount: '仍开仓只数',
  sectors: '持仓板块',
  empty: '纸面账尚未结算出日净值。',
  ctaTitle: '开通星球会员看完整账本',
  ctaDesc: '会员可看日净值表、开平仓流水，以及仍持仓的代码、成本、现价与净收益。',
  cta: '了解星球会员',
  positions: '当前仍持仓',
  daily: '日净值',
  events: '当天做了什么',
  pickDay: '点选交易日查看流水',
  noEvents: '这一天没有开平仓记录。',
  noPositions: '当前空仓。',
  code: '代码',
  name: '名称',
  cost: '成本',
  last: '现价',
  netPnl: '净收益',
  shares: '数量',
  price: '成交价',
  reason: '原因',
  cash: '现金',
  equity: '净值',
  marketValue: '市值',
  pnlDay: '日盈亏',
  pnlTotal: '累计',
}

const EN: Record<keyof typeof ZH, string> = {
  title: 'Wyckoff paper shadow ledger',
  subtitle: 'A paper account that mirrors the funnel. Not live fills.',
  disclaimer: 'The strategy books a Wyckoff-funnel paper ledger; not investment advice.',
  showcaseBadge: 'Showcase',
  fullBadge: 'Full ledger',
  navTitle: 'Cumulative NAV',
  periodPnl: 'Period P&L',
  periodPct: 'Period return',
  maxDrawdown: 'Max drawdown',
  winRate: 'Crude win rate',
  openCount: 'Open names',
  sectors: 'Sectors',
  empty: 'No daily NAV has been settled yet.',
  ctaTitle: 'Unlock the full paper ledger',
  ctaDesc: 'Members can see the daily NAV table, fill tape, and open-position cost, mark and net P&L.',
  cta: 'Planet membership',
  positions: 'Open positions',
  daily: 'Daily NAV',
  events: 'What happened that day',
  pickDay: 'Select a trading day to inspect fills',
  noEvents: 'No open or close events that day.',
  noPositions: 'Flat.',
  code: 'Code',
  name: 'Name',
  cost: 'Cost',
  last: 'Mark',
  netPnl: 'Net P&L',
  shares: 'Qty',
  price: 'Price',
  reason: 'Reason',
  cash: 'Cash',
  equity: 'Equity',
  marketValue: 'Market value',
  pnlDay: 'Day P&L',
  pnlTotal: 'Cumulative',
}

export type ShadowCopy = typeof ZH

export function shadowCopy(locale: Locale): ShadowCopy {
  return locale === 'zh-CN' ? ZH : EN
}
